=== TheSlashVII/ProjectJSON_JR_PROVEN/JSON_Project/src/json_schema/finalSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/city",
  "definitions": {
    "city": {
      "type": "object",
      "properties": {
        "documentName": {
          "type": "string"
        },
        "locality": {
          "type": "string"
        },
        "territory": {
          "type": "string"
        },
        "municipality": {
          "type": "string"
        },
        "municipalitycode": {
          "type": "string"
        },
        "territorycode": {
          "type": "string"
        }
      },
      "required": [
        "documentName",
        "locality",
        "territory",
        "municipality",
        "municipalitycode",
        "territorycode"
      ],
      "additionalProperties": false
    }
  }
}

=== TheSlashVII/ProjectJSON_JR_PROVEN/JSON_Project/src/citiesEsukadi.json
[{"documentName":"Bilbao","locality":"Bilbao","municipality":"Bilbao","territory":"Bizkaia","territorycode":"48","municipalitycode":"020"},{"documentName":"Astigarraga","locality":"Astigarraga","municipality":"Astigarraga","territory":"Gipuzkoa","territorycode":"20","municipalitycode":"903"},{"documentName":"Salvatierra/Agurain","locality":"Arrizala  Agurain/Salvatierra  Egileor  Alangua  Opakua","municipality":"Agurain/Salvatierra Agurain/Salvatierra Agurain/Salvatierra Agurain/Salvatierra Agurain/Salvatierra Agurain/Salvatierra","territory":"Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01 01 01 01","municipalitycode":"051 051 051 051 051 051"},{"documentName":"Barakaldo","locality":"San Vicente de Barakaldo  Errekatxo/El Regato","municipality":"Barakaldo Barakaldo","territory":"Bizkaia Bizkaia","territorycode":"48 48","municipalitycode":"013 013"},{"documentName":"Santurtzi","locality":"El Villar | Diseminado  Balparda | Diseminado  Santurtzi","municipality":"Santurtzi Santurtzi Santurtzi","territory":"Bizkaia Bizkaia Bizkaia","territorycode":"48 48 48","municipalitycode":"082 082 082"},{"documentName":"Ayala/Aiara","locality":"Izoria  Erbi | Diseminado  Luxo/Lujo | Diseminado  Luiaondo  Llanteno  Madaria | Diseminado  Maroño | Diseminado  Menagarai  Menoio  Murga  Ozeka | Diseminado  Olabezar | Diseminado  Quejana/Kexaa | Diseminado  Arespalditza/Respaldiza | Arespalditza / Res","municipality":"Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara Ayala/Aiara","territory":"Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01","municipalitycode":"010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010 010"},{"documentName":"Elvillar/Bilar","locality":"Elvillar/Bilar","municipality":"Elvillar/Bilar","territory":"Araba/Álava","territorycode":"01","municipalitycode":"023"},{"documentName":"Abadiño","locality":"Zelaieta | Abadiño-Zelaieta  Gaztelua | Diseminado  Gerediaga | Diseminado  Traña-Matiena  Mendiola | Diseminado  Muntsaratz  Urkiola | Diseminado","municipality":"Abadiño Abadiño Abadiño Abadiño Abadiño Abadiño Abadiño","territory":"Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia","territorycode":"48 48 48 48 48 48 48","municipalitycode":"001 001 001 001 001 001 001"},{"documentName":"Alegría-Dulantzi","locality":"Egileta  Alegría-Dulantzi","municipality":"Alegría-Dulantzi Alegría-Dulantzi","territory":"Araba/Álava Araba/Álava","territorycode":"01 01","municipalitycode":"001 001"},{"documentName":"Amurrio","locality":"Aloria  Amurrio  Artomaña  Baranbio  Tertanga  Larrinbe | Diseminado  Lekamaña  Lezama | Diseminado  Saratxo | Diseminado  Delika","municipality":"Amurrio Amurrio Amurrio Amurrio Amurrio Amurrio Amurrio Amurrio Amurrio Amurrio","territory":"Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01 01 01 01 01 01 01 01","municipalitycode":"002 002 002 002 002 002 002 002 002 002"},{"documentName":"Añana","locality":"Salinas de Añana/Gesaltza Añana  Atiega/Atiaga | Diseminado","municipality":"Añana Añana","territory":"Araba/Álava Araba/Álava","territorycode":"01 01","municipalitycode":"049 049"},{"documentName":"Aramaio","locality":"Arexola | Diseminado  Azkoaga | Diseminado  Barajuen | Diseminado  Etxaguen | Diseminado  Uribarri | Diseminado  Ibarra  Oleta  Untzilla | Diseminado  Gantzaga | Diseminado","municipality":"Aramaio Aramaio Aramaio Aramaio Aramaio Aramaio Aramaio Aramaio Aramaio","territory":"Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01 01 01 01 01 01 01","municipalitycode":"003 003 003 003 003 003 003 003 003"},{"documentName":"Vitoria-Gasteiz","locality":"Abetxuko  Zumeltzu  Ehari/Ali  Amarita  Andollu  Antezana/Andetxa | Antezana / Andetxa  Arangiz  Arkauti/Arcaute | Arkauti / Arcaute  Arkaia  Aretxabaleta  Argandoña  Ariñiz/Aríñez | Ariñiz / Aríñez  Armentia    Artatza Foronda  Askartza  Astegieta  Berro","municipality":"Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz Vitoria-Gasteiz","territory":"Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01","municipalitycode":"059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059 059"},{"documentName":"San Sebastián","locality":"Añorga  Igeldo  Landarbaso | Diseminado  Donostia / San Sebastián  Zubieta | Diseminado","municipality":"Donostia / San Sebastián Donostia / San Sebastián Donostia / San Sebastián Donostia / San Sebastián Donostia / San Sebastián","territory":"Gipuzkoa Gipuzkoa Gipuzkoa Gipuzkoa Gipuzkoa","territorycode":"20 20 20 20 20","municipalitycode":"069 069 069 069 069"},{"documentName":"Eibar","locality":"Aginaga | Diseminado  Arrate | Diseminado  Eibar  Maltzaga | Diseminado","municipality":"Eibar Eibar Eibar Eibar","territory":"Gipuzkoa Gipuzkoa Gipuzkoa Gipuzkoa","territorycode":"20 20 20 20","municipalitycode":"030 030 030 030"},{"documentName":"Abanto y Ciérvana-Abanto Zierbena","locality":"La Balastera  Abanto  Las Calizas | Diseminado  El Campillo  La Florida | Diseminado  Gallarta  Picón | Diseminado  Santa Juliana  Triano  Las Carreras  Los Castaños  Las Cortes | Diseminado  Cotorrio | Diseminado  Murrieta  Putxeta  San Pedro  Sanfuentes","municipality":"Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena Abanto y Ciérvana-Abanto Zierbena","territory":"Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia Bizkaia","territorycode":"48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48","municipalitycode":"002 002 002 002 002 002 002 002 002 002 002 002 002 002 002 002 002 002"},{"documentName":"Aduna","locality":"Aduna","municipality":"Aduna","territory":"Gipuzkoa","territorycode":"20","municipalitycode":"002"},{"documentName":"Abaltzisketa","locality":"Abaltzisketa","municipality":"Abaltzisketa","territory":"Gipuzkoa","territorycode":"20","municipalitycode":"001"},{"documentName":"Armiñón","locality":"Estavillo  Armiñón  Lacorzana","municipality":"Armiñón Armiñón Armiñón","territory":"Araba/Álava Araba/Álava Araba/Álava","territorycode":"01 01 01","municipalitycode":"006 006 006"},{"documentName":"Ajangiz","locality":"Kanpantxu | Diseminado  Mendieta | Diseminado","municipality":"Ajangiz Ajangiz","territory":"Bizkaia Bizkaia","territorycode":"48 48","municipalitycode":"911 911"},{"documentName":"Alonsotegi","locality":"Irauregi  Arbuio  Alonsotegi","municipality":"Alonsotegi Alonsotegi Alonsotegi","territory":"Bizkaia Bizkaia Bizkaia","territorycode":"48 48 48","municipalitycode":"912 912 912"},{"documentName":"Amorebieta-Etxano","locality":"Autzagana | Diseminado  Aldana | Diseminado  Boroa | Diseminado  Etxano | Diseminado  Euba  Bernagoitia | Diseminado  Amorebi
